export * from "./field-type.enum";
export * from "./format-time.enum";
export * from "./menu-items.type";
export * from "./param-search.type";
export * from "./permissions.type";

export enum SystemFeatures {
  QuanLyNguoiDung = "ManagerUsers",
  QuanLyVaiTro = "ManagerRoles",
  QuanLyDonVi = "ManagerUnits",
  QuanLyQuyen = "ManagerPermissions",
  TroopReports = "TroopReports",
  ManagerRegisterLeave = "ManagerRegisterLeave",
  ManagerGuardDutty = "ManagerGuardDutty",
  ManagerDuttySetting = "ManagerDuttySetting",
  ManagerPositions = "ManagerPositions",
  ManagerProgresses = "ManagerProgresses",
  ManagerDocuments = "ManagerDocuments",
  ManagerTrainings = "ManagerTrainings",
  ManagerPersonalDiarys = "ManagerPersonalDiarys",
  WorkCalendar = "WorkCalendar",
  ManagerExperiences = "ManagerExperiences",
  ManagerVehicle = "ManagerVehicle",
  RegisterVehicle = "RegisterVehicle",
  VehicleCommand = "VehicleCommand",
  DeliveryBill = "DeliveryBill",
  MeetingBook = "MeetingBook",
  ManagerFuel = "ManagerFuel",
  ManagerWorkAddress = "ManagerWorkAddress",
  ManagerTask = "ManagerTask",
  ManagerTrackDiscipline = "ManagerTrackDiscipline",
  StatisticDocument = "StatisticDocument",
  ManagerTrackWork = "ManagerTrackWork",
  AccessControl = "AccessControl",
  StatisticWebC86 = "StatisticWebC86",
  GoingCall = "GoingCall",
  InComingCall = "InComingCall",
  ManagerTypeBook = "ManagerTypeBook",
  KHHLCDNam = "KHHLCDNam",
  KHHLCDGD1 = "KHHLCDGD1",
  KHHLCDGD2 = "KHHLCDGD2",
  KHHLCDThang = "KHHLCDThang",
  TTBHLCDTuan = "TTBHLCDTuan",
  MLHLCDNam = "MLHLCDNam",
  HDKHHLCDNam = "HDKHHLCDNam",
  HDKHHLCDGD1 = "HDKHHLCDGD1",
  HDKHHLCDGD2 = "HDKHHLCDGD2",
  TKHLCum = "TKHLCum",
  TKHLTrungTam = "TKHLTrungTam",
  TKHLBTL = "TKHLBTL",
  BCHLTuan = "BCHLTuan",
  BCHLThang = "BCHLThang",
  BCHLQuy = "BCHLQuy",
  BCHL6Thang = "BCHL6Thang",
  BCHL9Thang = "BCHL9Thang",
  BCHLNam = "BCHLNam",
  ThongQuaGiaoAn = "ThongQuaGiaoAn",
  GiaoAnHuanLuyen = "GiaoAnHuanLuyen",
  RutKinhNghiemHL = "RutKinhNghiemHL",
  SoHocTapCaNhan = "SoHocTapCaNhan",
  EvaluateTraining = "EvaluateTraining",
  ManagerObjectTraining = "ManagerObjectTraining",
  ManagerSystem = "ManagerSystem",
}

export enum SystemAction {
  View = "View",
  Edit = "Edit",
  Approve = "Approve",
  Report = "Report",
  UnitApprove = "UnitApprove",
}